# PostgreSQL DB 설정 (Secret 대체)
datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"

volume-path:
  persistent-volume-data: "C:\\data\\local\\pv"
  pod-volume-data: "C:\\data\\local\\pod"
